name: Python - run test suite

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'python/**'
      - 'tests_data/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'python/**'
      - 'tests_data/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  unit-testing:
    strategy:
      matrix:
        python-version: [ "3.9.x" ]
        os: [ "windows-latest" ]
        # TODO: add ubuntu:20.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # pin@v5
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.4.7/install.sh | sh

      - name: Check python version
        working-directory: python
        run: uv run --python 3.9 python --version
        
