name: Python - run test suite

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'python/**'
      - 'tests_data/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'python/**'
      - 'tests_data/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  unit-testing:
    strategy:
      matrix:
        python-version: [ "3.8.x", "3.9.x", "3.10.x", "3.11.x", "3.12.x" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        # TODO: add ubuntu:20.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # pin@v5
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.4.7/install.sh | sh

      - name: Install all projects dependencies (with the requested python version)
        working-directory: python
        run: uv sync --python $(which python3) --all-extras --dev

      - name: Run ruff check
        working-directory: python
        run: uv run --python $(which python3) ruff check --verbose

      - name: Run ruff format --check
        working-directory: python
        run: uv run --python $(which python3) ruff format --check --verbose

      - name: Run mypy
        working-directory: python
        run: uv run --python $(which python3) mypy src/magika tests

      - name: Run the python tests suite
        working-directory: python
        run: uv run --python $(which python3) pytest tests -m "not slow"

      - name: Run magika --version
        working-directory: python
        run: uv run magika --version
        shell: bash # Allows for cross-platform

      - name: Run magika with tests_data
        working-directory: python
        # TODO(https://github.com/google/magika/issues/780): Remove "grep || exit 1" when fixed.
        run: '(uv run magika -r ../tests_data/basic | grep "code\.asm.*Assembly") || exit 1'

      - name: Run "magika cli" quick tests
        working-directory: python
        run: uv run scripts/run_quick_test_magika_cli.py

      - name: Run "magika module" quick tests
        working-directory: python
        run: uv run scripts/run_quick_test_magika_module.py
